/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V raygen.rgen -o raygen.rgen.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V multiReflections.rgen -o multiReflections.rgen.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V closesthit.rchit -o closesthit.rchit.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V miss.rmiss -o miss.rmiss.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V shadow.rmiss -o shadow.rmiss.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V shadow.rchit -o shadow.rchit.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V diffuseRaygen.rgen -o diffuseRaygen.rgen.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V diffuseMultiReflections.rgen -o diffuseMultiReflections.rgen.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V diffuseClosesthit.rchit -o diffuseClosesthit.rchit.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V diffuseMiss.rmiss -o diffuseMiss.rmiss.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V diffuseShadow.rmiss -o diffuseShadow.rmiss.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V diffuseShadow.rchit -o diffuseShadow.rchit.spv
