/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V raygen.rgen -o raygen.rgen.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V multiReflections.rgen -o multiReflections.rgen.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V closesthit.rchit -o closesthit.rchit.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V miss.rmiss -o miss.rmiss.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V shadow.rmiss -o shadow.rmiss.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V shadow.rchit -o shadow.rchit.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V hybridRaygen.rgen -o hybridRaygen.rgen.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V hybridMultiReflections.rgen -o hybridMultiReflections.rgen.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V hybridClosesthit.rchit -o hybridClosesthit.rchit.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V hybridMiss.rmiss -o hybridMiss.rmiss.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V hybridShadow.rmiss -o hybridShadow.rmiss.spv
/home/mharrer/Documents/libraries/VulkanSDK/1.1.106.0/x86_64/bin/glslangValidator -V hybridShadow.rchit -o hybridShadow.rchit.spv
